version: '3.8'

services:

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${GRAPH_DB_USER:-neo4j}/${GRAPH_DB_PASSWORD:-KGdkfCHtVumyMN}
      - NEO4JLABS_PLUGINS=["graph-data-science"]  # Enable GDS plugin
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - ./ops/neo4j/plugins:/plugins  # Mount the directory with the GDS JAR

  scheduler:
    build:
      context: ../
      dockerfile: Dockerfile
    command: ["celery", "-A", "scheduler", "worker", "--beat", "-E", "--loglevel=info"]
    depends_on:
      - redis
      - neo4j
    environment:
      - APIFY_API_KEY=apify_api_eZrqixGZNbC3k4h9xlKTMsym7eCqHZ0F6rN5
      - GRAPH_DB_URL=bolt://neo4j:7687
      - GRAPH_DB_USER=neo4j
      - GRAPH_DB_PASSWORD=KGdkfCHtVumyMN
      - SCRAPE_START_DATE=2024-07-01
      - MAX_ITEMS=1200
      - SCRAPE_TOKEN=PEPE
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    volumes:
      - ./logs:/logs

  scheduler-ui:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    command: ["celery", "flower", "--broker=redis://redis:6379/0"]
    depends_on:
      - redis
      - scheduler
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  neo4j-data:
    name: neo4j-data
  neo4j-logs:
    name: neo4j-logs
